### ISSUE TITLE
Please delete specific branches from Fullbrik/Fright-of-the-Fridge-Goldsrc.

### ISSUE THREAD

**Issue by malortie** [Fullbrik/tetris#1]
@Fullbrik 

I apologize for opening this issue here, as it is unrelated to the current repository, but it is not possible to open issues on your repository [Fullbrick/Fright-of-the-Fridge-Goldsrc](https://github.com/Fullbrik/Fright-of-the-Fridge-Goldsrc), and there is no way to contact you via email.

You have a repository [Fullbrick/Fright-of-the-Fridge-Goldsrc](https://github.com/Fullbrik/Fright-of-the-Fridge-Goldsrc), which is a fork of my repository [malortie/halflife](https://github.com/malortie/halflife).

Recently, I deleted 3 branches from my repository:

- branch-malortie-bshift
- branch-malortie-op4
- mod-hl-bshiftunlocked

The first two branches contained source code of some of my earlier (and unfinished for the most part) projects, which aimed to recode Half-Life: Opposing Force and Half-Life: Blue shift from scratch, using Valve Software's Half-Life SDK. The last branch contained source code for my Steampipe patch for the mod Blue Shift: Unlocked.

I deleted these branches because I have been recently feeling more concerned about the legality of such projects. Both games were developed by Gearbox Software and according to [Gearbox's EULA](https://www.gearboxsoftware.com/eula/), any 'reproduction' and or 'derived' project is prohibited.

Because you forked my repository before I deleted these branches, your fork still contains one or more of the branches listed above. Could you please delete these branches from [Fullbrick/Fright-of-the-Fridge-Goldsrc](https://github.com/Fullbrik/Fright-of-the-Fridge-Goldsrc)?

**Comment by Fullbrik** [comment]
done
